config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "quotes#index"
  
  post 'addresses/import', to: 'addresses#import', as: 'import_addresses'
  get '/quotes/generate', to: 'quotes#generate', as: 'generate_quote'
  get '/addresses/search', to: 'addresses#search', as: 'search_addresses'
  resources :addresses
  resources :quotes
  
  
  
end

app/models/address.rb
require 'elasticsearch/model'

class Address < ApplicationRecord
require 'csv'

	has_one :quote
 has_and_belongs_to_many :requesters

	include Elasticsearch::Model
	include Elasticsearch::Model::Callbacks
	
     
  settings index: { number_of_shards: 1 } do
	  mappings dynamic: 'false' do
	    indexes :street, analyzer: 'english'
	    indexes :city, analyzer: 'english'
	    indexes :state, analyzer: 'english' 
	    indexes :zip, analyzer: 'english'
	  end
	end
	
	def as_indexed_json(options={})
	    as_json(
	    	only: [:street, :city, :state, :zip]
	    )
	 end
	 
   ## Address.all.import force: true
   
   def self.import_addresses(file)
   	CSV.foreach(file.path, headers: true) do |row|
   		Address.create!(row.to_hash)
   	end
   end
   
      def get_mowing_cost
    	if self.square_feet < 4000
    		return 24.0
    	elsif self.square_feet < 10000
	        return 29.0
	    elsif self.square_feet < 14000
	    	return 34.0
	    end
	  end
	  
	  def get_spraying_cost
	    if self.square_feet < 4000
    		return 24.0
    	elsif self.square_feet < 10000
	        return 29.0
	    elsif self.square_feet < 14000
	    	return 34.0
	    end
	  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :requester
  
  after_create :send_notification
  
  
  def send_notification
    notification = SendGridMailer.new()
    notification.send_notification
  
  end
end

app/models/requester.rb
class Requester < ApplicationRecord
    
    before_create :generate_cookie, :set_count
    
    has_and_belongs_to_many :addresses
    has_many :quotes
    
    protected

    def generate_cookie
        self.cookie = loop do
            random_token = SecureRandom.urlsafe_base64(nil, false)
            break random_token unless Requester.exists?(cookie: random_token)
        end
    end
    
    def set_count
        self.count = 1
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
    

skip_before_action :verify_authenticity_token
 
 before_action :authenticate_user!, :except => [:search]
  
	
    def new
        @address = Address.new
    end
    
    def index
        Address.__elasticsearch__.delete_index!
        Address.__elasticsearch__.create_index!
        Address.all.import force: true
	          
        
    end
    
    def edit
        
    end
    
    def search
       
	   
        #Address.all.import force: true
        @addresses = Address.all
        puts @addresses.size
        
        search_params = {
            query: {
              multi_match: {
                query: "#{params[:q]}",
                fields: ["street", "state"]
              }
            }
          }
        
          @addresses= Address.__elasticsearch__.search(search_params, size: 1).results()
         
          
        
    end
    
    def import
        Address.import_addresses(params[:file])
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :authenticate_user!, :except => [:generate]
    def index
        if params[:page].blank?
            page = 1
        else
            page = params[:page].to_i
        end
        @quotes = Quote.all.order(created_at: :desc).page(page).per(15)
    end
    
    def destroy
       quote = Quote.find(params[:id])
       quote.destroy!
       
       redirect_to quotes_path()
    end
    
    def new
        
    end
    
    def generate
       
        requester = Requester.find_by(cookie: cookies.encrypted[:token])
        
        if requester.blank?
            #attempt to find requester. Create if necessary.
            requester = Requester.find_by(ip: request.remote_ip)
            
            if requester.blank?
               requester = Requester.find_by(email: params[:email]) 
            end
            
            #create cookie.
            if requester.blank?
                requester = create_requester(request.remote_ip, params[:email])
                cookies.permanent.encrypted[:token] = requester.cookie
            else
                cookies.permanent.encrypted[:token] = requester.cookie  
            end
            
        end
        
        @quote = false
        @address = Address.find_by(id: params["address_id"])
        
        
        if @address.present?
            requester_address = requester.addresses.find_by(id: @address.id.to_s)
            if requester.addresses.count < 2 && requester_address.blank?
                @quote = true
                requester.addresses << @address
            elsif requester_address.present?
                @quote = true
            else
                @message = "You cannot request more than 2 addresses. If you need further assistance please call us at the number below."
            end
        else
            @quote = requester.quotes.create(name: params[:name], address: params[:address], phone: params[:phone], email: params[:email])
            @message = "We were unable to find your address in our database. We will contact you within 24 hours with a quote!"
        end
        
        if @quote == true
           @lawn_mowing_price = @address.get_mowing_cost
           @lawn_spraying_price = @address.get_spraying_cost
        end
        
        
        
        puts requester.addresses.count
         
    end
    
    private
    def create_requester(ip, email)
       requester = Requester.create(ip: ip, email: email) 
    end
    
    
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/addresses/_address.html.erb
<li data-id="<%= address.id %>" data-address="<%= address.street %> <%= address.city %> <%= address.state %>">
<div class="row results-container">
    <div class="col-md-8 address-container">
         <span class="address"><%= address.street %> <%= address.city %> <%= address.state %> <span style="color:white; font-size:80%;">(click me)</span></span>                   
    </div>
    <div class="col-md-1">
         <img src="https://maps.googleapis.com/maps/api/streetview?size=150x50&location=<%= address.street %> <%= address.city %> <%= address.state %>&fov=180&heading=0&pitch=0&key=AIzaSyB0AVax3Llhouag6fE6KH8JGsEANiDMnsk">                                    
    </div>
</div>
</li>

app/views/addresses/index.html.erb
<%= form_tag import_addresses_path, multipart: true do %>
<%= file_field_tag :file%>
<%= submit_tag "Import CSV" %>
<% end %>

app/views/addresses/search.js.erb
<% if @addresses.size > 0 %>
jQuery("#results").html("");
jQuery("<%= escape_javascript(render :partial => "address", collection: @addresses) %>").appendTo("#results");
jQuery( "#results" ).removeClass( "hidden" );
jQuery( "#select-address" ).removeClass( "hidden" );
jQuery( "#no-address" ).removeClass( "hidden" );
<% else %>
jQuery("#results").html("");
jQuery("<li class='no-add-found'>No Addresses Found.</li>").appendTo("#results");
jQuery( "#results" ).addClass( "hidden" );
jQuery( "#select-address" ).addClass( "hidden" );
jQuery( "#no-address" ).addClass( "hidden" );
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lanwjox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js" integrity="sha256-xI/qyl9vpwWFOXz7+x/9WkG5j/SVnSw21viy8fWwbeE=" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    
  </head>

  <body>
    
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  
    <%= yield %>
    
  
  
    
    
    
   
  </body>
</html>

app/views/quotes/_no_quote.html.erb
<div class="container qc" style="padding:0px !important; width:100%;">
      <div class="row">
        <div class="col-md-12">
            <div id="quote-container">
                <span style="font-size:100%;display:block;text-align:center;font-weight:900;"><%= @message %></span>
                <span style="text-align:center;display:block;padding:8%;"><a href="tel:+1901LAWNJOX" style="font-size:150%;font-weight:900;">Call Us: 901-LAWN-JOX</a></span>
             </div>
        </div>
    </div>
</div>
    
    

app/views/quotes/_quote_form.html.erb
<div class="container qc" style="padding:0px !important; width:100%;">
      <div class="row">
        <div class="col-md-12">
            <div id="quote-container">
                <span style="font-size:100%;display:block;text-align:center;font-weight:900;">Select From The Service Options Below!</span>
                <span style="font-size:100%;display:block;text-align:center;font-style:italic;font-size:13px;">Address: <%= @address.street %> <%= @address.city %> <%= @address.state %></span>
                
             <FORM METHOD="POST" ACTION="https://ww9.aitsafe.com/cf/addmulti.cfm" target="_parent">
                <INPUT TYPE="HIDDEN" NAME="userid" VALUE="B1190129">
                <div class="lawn-mowing">
                  <div class="top-section">
                       <span>Lawn Mowing</span>
                       <img src="https://lawnjox.com/wp-content/uploads/2018/03/lawn-mower.png" class="scale-with-grid" alt="lawn-mower"> 
                       
                  </div>
                  <div class="bottom-section">
                        <input id="mowing" type="checkbox" style="vertical-align:middle;width:15px;height:15px;" checked><span class="service-text" style="color:white;font-weight:900;">Lawn Mowing <%= number_to_currency(@address.mowing_price.round(2)) %> (Weekly)</span>  
                        <INPUT id="lawn-mowing-qty" TYPE="hidden" NAME="qty1" value="1"> 
                        <INPUT TYPE="HIDDEN" NAME="product1" VALUE="Lawn Mowing">
                        <INPUT TYPE="HIDDEN" NAME="price1" VALUE="<%=  @address.mowing_price.round(2) %>">
                  </div>
                    
                </div>
                
                <div class="lawn-mowing">
                  <div class="top-section">
                       <span>Lawn Care (spraying)</span>
                       <img src="https://lawnjox.com/wp-content/uploads/2018/02/lawn.png" class="scale-with-grid" alt="lawn">  
                  </div>
                  <div class="bottom-section">
                      <input id="spraying" type="checkbox" style="vertical-align:middle;width:15px;height:15px;" checked><span class="service-text" style="color:white;font-weight:900;">Lawn Spraying <%= number_to_currency(@address.spraying_price.round(2)) %></span>  
                      <INPUT id="lawn-spraying-qty" TYPE="hidden" NAME="qty2" value="1">
                      <INPUT TYPE="HIDDEN" NAME="product2" VALUE="Lawn Care (Spraying)">
                      <INPUT TYPE="HIDDEN" NAME="price2" VALUE="<%= @address.spraying_price.round(2) %>">
                  </div>
                </div>
                    
                
               
                <div class="row" style="text-align:center;">
                          <div class="col-md-12">
                              
                              <button type="submit" class="form-control btn-default">Proceed to Checkout</button>
                          </div>
                      </div>
                      <div style="text-align:center;">
                        <span class="step"></span>
                        <span class="step active"></span>
                        <span class="step"></span>
                      </div>
                </FORM>
                </div>
        </div>
    </div>
</div>

    

app/views/quotes/generate.js.erb
jQuery("#instant-quote").html("");
<% if @quote == true %>
jQuery("<%= escape_javascript(render :partial => "quote_form") %>").appendTo("#instant-quote");
<% else %>
    jQuery("<%= escape_javascript(render :partial => "no_quote") %>").appendTo("#instant-quote");
<% end %>

app/views/quotes/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
          <h2>Quotes</h2>
          <%= paginate @quotes %>  
          <table class="table table-striped">
            <thead>
              <tr>
                <th>ID</th>
                <th>Date</th>
                <th>Name</th>
                <th>Address</th>
                <th>Phone Number</th>
                <th>Email</th>
                <th>Delete</th>
              </tr>
            </thead>
            <tbody>
                <% @quotes.each do |i| %>
                    <tr>
                        <td><%= i.id %></td>
                        <td><%= i.created_at.strftime("%A, %B %d, %Y") %></td>
                        <td><%= i.name %></td>
                        <td><%= i.address %></td>
                        <td><%= i.phone %></td>
                        <td><%= i.email %></td>
                        <td><%= link_to 'Delete',  quote_path(i),  method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                <% end %>
            </tbody>
          </table>
          <%= paginate @quotes %>
        </div>
    </div>
</div>